export const CORS_DEV_TOKEN = 'CORS_DEV';
export const CORS_ORIGIN_TOKEN = 'CORS_ORIGIN';
export const COOKIE_SECRET_TOKEN = 'COOKIE_SECRET';

export const ENABLE_GLOBAL_EXCEPTION_LOGGING_IN_CONSOLE_TOKEN = 'ENABLE_GLOBAL_EXCEPTION_LOGGING_IN_CONSOLE';
export const ENABLE_HTTP_EXCEPTION_LOGGING_IN_CONSOLE_TOKEN = 'ENABLE_HTTP_EXCEPTION_LOGGING_IN_CONSOLE';
export const ENABLE_ALL_WS_EXCEPTION_LOGGING_IN_CONSOLE_TOKEN = 'ENABLE_ALL_WS_EXCEPTION_LOGGING_IN_CONSOLE';
